name: CI

on:
  push:
    branches: [ main, master, lab6 ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test
        run: mvn -B clean verify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: photoprint-app
          path: target/*.jar